export enum UserRole {
  ADMIN = 'ADMIN',
  AGENT = 'AGENT',
  CUSTOMER = 'CUSTOMER',
}

export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  WAITING = 'WAITING', // created, no one connected yet
  ACTIVE = 'ACTIVE', // at least one participant connected
  ENDED = 'ENDED',
  CANCELLED = 'CANCELLED',
}

export enum ParticipantRole {
  AGENT = 'AGENT',
  CUSTOMER = 'CUSTOMER',
  OBSERVER = 'OBSERVER', // admin silently monitoring
}

export enum ParticipantStatus {
  INVITED = 'INVITED',
  CONNECTED = 'CONNECTED',
  RECONNECTING = 'RECONNECTING',
  DISCONNECTED = 'DISCONNECTED',
  LEFT = 'LEFT',
}

export enum RecordingStatus {
  IDLE = 'IDLE',
  RECORDING = 'RECORDING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum MessageType {
  TEXT = 'TEXT',
  FILE = 'FILE',
  SYSTEM = 'SYSTEM',
}

export enum EventType {
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_ENDED = 'SESSION_ENDED',
  PARTICIPANT_JOINED = 'PARTICIPANT_JOINED',
  PARTICIPANT_LEFT = 'PARTICIPANT_LEFT',
  PARTICIPANT_RECONNECTED = 'PARTICIPANT_RECONNECTED',
  PARTICIPANT_DROPPED = 'PARTICIPANT_DROPPED',
  RECORDING_STARTED = 'RECORDING_STARTED',
  RECORDING_STOPPED = 'RECORDING_STOPPED',
  RECORDING_READY = 'RECORDING_READY',
  MEDIA_TOGGLED = 'MEDIA_TOGGLED',
  SCREEN_SHARE_STARTED = 'SCREEN_SHARE_STARTED',
  SCREEN_SHARE_STOPPED = 'SCREEN_SHARE_STOPPED',
  FILE_SHARED = 'FILE_SHARED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  ERROR = 'ERROR',
}

export enum MediaKind {
  AUDIO = 'audio',
  VIDEO = 'video',
}

export enum AppMediaKind {
  CAM = 'cam',
  MIC = 'mic',
  SCREEN = 'screen',
}

export enum Sentiment {
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEGATIVE = 'NEGATIVE',
  FRUSTRATED = 'FRUSTRATED',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  CREATE_SESSION = 'CREATE_SESSION',
  END_SESSION = 'END_SESSION',
  FORCE_END_SESSION = 'FORCE_END_SESSION',
  GENERATE_INVITE = 'GENERATE_INVITE',
  REVOKE_INVITE = 'REVOKE_INVITE',
  START_RECORDING = 'START_RECORDING',
  STOP_RECORDING = 'STOP_RECORDING',
  DOWNLOAD_RECORDING = 'DOWNLOAD_RECORDING',
  UPLOAD_FILE = 'UPLOAD_FILE',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
}
